### ISSUE TITLE
单元测试testParseObjectReleased()未通过

### ISSUE THREAD

**Issue by L-JINBIN** [HarlonWang/quickjs-wrapper#71]
java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at com.whl.quickjs.wrapper.QuickJSTest.testParseObjectReleased(QuickJSTest.java:1343)

**Comment by HarlonWang** [comment]
我这边没有复现你的情况，方便的话，可以多补充一些其他信息，例如设备、系统、测试环境之类的信息。
![image](https://github.com/user-attachments/assets/f660022d-8247-4994-8e6f-e373101c2629)

**Comment by L-JINBIN** [comment]
我手头两台红米设备均测试失败，模拟器和几台其他牌子的手机测试成功。
1. 红米K60：MIUI 14.0.28，Android 13，安全更新2023-10-01
2. 红米K70：澎湃OS 1.0.16.0.UNKCNXM，Android 14，安全更新2024-05-01

```
QuickJS memory usage -- BigNum 2021-03-27 version, 64-bit, malloc limit: -1
  696 + 72  JSRuntime
  480 + 32  JSContext
   72 + 8   JSObject
   16 + 0   JSString
  128 + 0   JSFunctionBytecode
JSObject classes
     52   1 Object
      1   2 Array
      1   4 Number
      1   5 String
      1   6 Boolean
     91  12 Function
     26  13 Function
      1  15 Function
      1  48 <null>
      1     other
NAME                    COUNT     SIZE
memory allocated         1092   109080  (99.9 per block)
memory used              1102    87035  (8 overhead, 20.0 average slack)
atoms                     575    22413  (39.0 per atom)
strings                     5      671  (134.2 per string)
objects                   176    12672  (72.0 per object)
  properties              880    15760  (5.0 per object)
  shapes                   55    12488  (227.1 per shape)
bytecode functions         22    15181
  bytecode                 22     2606  (118.5 per function)
  pc2line                  22      228  (10.4 per function)
C functions                91
arrays                      1
  fast arrays               1
  elements                  0        0  (0.0 per fast array)
```

**Comment by HarlonWang** [comment]
我这边用小米13复现了，报错可以先忽略，实际没有任何影响，猜测应该是32位和64位的内存分配大小不同，这个测试 case 需要再重新完善下

**Comment by HarlonWang** [comment]
我这边把测试的最大值调大了，避免受初始内存的大小影响，你可以用最新代码再验证下
